id: ICAA11D1A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:30:21+00:00'
last_modified: '2022-06-08T02:18:16.387205+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24937
  title: གཙུག་ལག་པོད་བཞི་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F972:
      image_group_id: I1KG24939
      title: ''
      total_pages: 662
      order: 1
      base_file: F972.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
