id: P004611
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24937
  title: གཙུག་ལག་པོད་བཞི་མ།
  author: ''
  volumes:
    4d81568379434ac0a8bdeee7dbca865c:
      image_group_id: I1KG24939
      title: ''
      volume_number: 1
      total_pages: 662
      base_file: v001.txt
